unit_tests:
  stage: test
  image:
    name: condaforge/mambaforge:23.1.0-4
  variables:
    CONDA_PKGS_DIRS: "$CI_PROJECT_DIR/.conda-pkgs-cache/"
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PRE_COMMIT_HOME: "$CI_PROJECT_DIR/.cache/pre-commit"
  cache:
    key: test-cache
    paths:
      - $PRE_COMMIT_HOME
      - $CONDA_PKGS_DIRS/*.conda
      - $CONDA_PKGS_DIRS/*.tar.bz2
      - $CONDA_PKGS_DIRS/urls*
      - $CONDA_PKGS_DIRS/cache
      - $PIP_CACHE_DIR
  script:
    - mamba env create -f environment_deploy.yaml -v
    - mamba init bash
    - source ~/.bashrc
    - conda run -n ca-plugin pre-commit run --all-files
    - conda run -n ca-plugin pytest --ignore=$CONDA_PKGS_DIRS .

docker_build_deploy:
  stage: deploy
  only:
    - main
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"auth\":\"$(printf "%s:%s" "${CI_DOCKER_USER}" "${CI_DOCKER_TOKEN}" | base64 | tr -d '\n')\"}}}}" > /kaniko/.docker/config.json
    - echo "${CI_JOB_TOKEN}" > /kaniko/CI_JOB_TOKEN
    - >
      if [ -z ${CI_COMMIT_TAG+x} ]; then
        /kaniko/executor \
          --context "${CI_PROJECT_DIR}" \
          --dockerfile "${CI_PROJECT_DIR}/Dockerfile.Kaniko" \
          --destination "docker.io/heigit/ca-${CI_PROJECT_NAME}:devel"
      else
        /kaniko/executor \
          --context "${CI_PROJECT_DIR}" \
          --dockerfile "${CI_PROJECT_DIR}/Dockerfile.Kaniko" \
          --destination "docker.io/heigit/ca-${CI_PROJECT_NAME}:devel" \
          --destination "docker.io/heigit/ca-${CI_PROJECT_NAME}:${CI_COMMIT_TAG}"
      fi
