name: ca-ghg-emission-from-lulc-change
channels:
  - conda-forge
dependencies:
  - geojson-pydantic=1.0.1
  - pip=23.2.1
  - pydantic=2.3.0
  - pytest=7.4.2
  - python=3.11.5
  - matplotlib=3.8.0
  - shapely=2.0.2
  - pip:
      - git+https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.gistools.geog.uni-heidelberg.de/climate-action/climatoology.git@v2.4
      - ruff==0.0.280
      - geopandas==0.14.0
      